version: '3.2'

services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
#    volumes:
#      - ./docker/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
#      - ./docker/grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
#      - ./docker/grafana/dashboards/demo.json:/etc/grafana/provisioning/dashboards/demo.json
#      - ./docker/grafana/dashboards/create_session.json:/etc/grafana/provisioning/dashboards/create_session.json
#      - ./docker/grafana/dashboards/drop_session.json:/etc/grafana/provisioning/dashboards/drop_session.json

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'

  influxdb:
      image: influxdb
      ports:
        - "8086:8086"
      volumes:
        - ./docker/influxdb:/var/lib/influxdb